### ISSUE TITLE
Add support for Gitpod 

### ISSUE THREAD

**Issue by jlengrand** [adyen-examples/checkoutCreate#62]
In many of our samples, we add support for Gitpod, which allows our merchants to have access to a cloud dev environment running the samples using their test accounts in one click (and a one time setup).

I believe it could be interesting to have it available as well here. Here is another example : https://github.com/adyen-examples/adyen-python-online-payments.

The PR is in #55

**Comment by anamotaadyen** [comment]
Agreed. Merged PR :)
