### ISSUE TITLE
Methods with a redirect link back to locahost:8080

### ISSUE THREAD

**Issue by jlengrand** [adyen-examples/checkoutCreate#67]
Methods like iDeal with a redirect link back to http://localhost:8080, which won't work any more as soon as you deploy somewhere else. 

You could use a dynamic redirect URL for this, like for example in our [Python sample](https://github.com/adyen-examples/adyen-python-online-payments/blob/60ddd11ca8e1d2d8d1a4d25336a1284b8fd71dea/app/main/sessions.py#L18)

**Comment by anamotaadyen** [comment]
Please let me know if this fixes the flow
